### ISSUE TITLE
Symlink in .bin folder for cli

### ISSUE THREAD

**Issue by maxvipon** [f0rmat1k/bemy#10]
Look at the popular libs with cli – all of them have symlink in `node_modules/.bin` folder:
![2015-03-12_2112](https://cloud.githubusercontent.com/assets/871596/6622137/88ee4588-c8fc-11e4-85da-a35c2d822e7b.png)

**Comment by f0rmat1k** [comment]
Thank you, I'll add it.

**Comment by f0rmat1k** [comment]
Added with 1.4.2.

**Comment by maxvipon** [comment]
Thanks!
