### ISSUE TITLE
Templates in custom .bemy.json looked in module's dir

### ISSUE THREAD

**Issue by maxatwork** [f0rmat1k/bemy#22]
When I specify custom template in my `.bemy.json` file, `bemy` tries to use a template in it's own dir (i.e. `~/.nvm/v0.10.36/lib/node_modules/bemy/`).
I think that the searching in `.bemy.json` location is much more correct, because in this case you can specify both custom config and custom templates for the project (i.e. by placing the `.bemy.json` in project's root and placing templates to `.bemy` dir at the project's root).

**Comment by f0rmat1k** [comment]
v. 3.2.2, thank you
